apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app
  namespace: employee-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-app
          image: pddocker7033/myapp:v2
          ports:
            - containerPort: 8089   # match your Spring Boot port

          envFrom:
            - configMapRef:
                name: employee-config

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"