apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-app
  namespace: employee-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: employee-app

  template:
    metadata:
      labels:
        app: employee-app

    spec:
      containers:
        - name: employee-app

          image: pddocker7033/myapp:v4

          imagePullPolicy: Always

          ports:
            - containerPort: 8089

          envFrom:
            - configMapRef:
                name: employee-config

            - secretRef:
                name: employee-secret