apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-backend
  namespace: employee-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: employee-backend

  template:

    metadata:
      labels:
        app: employee-backend

    spec:

      containers:

      - name: employee-backend

        image: employee-backend:1.0

        imagePullPolicy: Never

        ports:
        - containerPort: 8081

        envFrom:
        - configMapRef:
            name: employee-config

        - secretRef:
            name: employee-secret